In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("dataset-tags.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'dataset-tags.csv'

In [2]:
import pandas as pd
import numpy as np
df = pd.read_csv("dataset-tags.csv")
df.head()

title                 tags   
0  Flask-SQLAlchemy - When are the tables/databas...  ['python', 'mysql']  \
1        Combining two PHP variables for MySQL query     ['php', 'mysql']   
2  'Counting' the number of records that match a ...     ['php', 'mysql']   
3  Insert new row in a table and auto id number. ...     ['php', 'mysql']   
4             Create Multiple MySQL tables using PHP     ['php', 'mysql']   

   mysql  python  php  
0      1     1.0  0.0  
1      1     0.0  1.0  
2      1     0.0  1.0  
3      1     0.0  1.0  
4      1     0.0  1.0

In [3]:
df.dtypes

title      object
tags       object
mysql       int64
python    float64
php       float64
dtype: object

In [4]:
df['mysql'] = df['mysql'].astype(float)

In [8]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score,hamming_loss
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
!pip install scikit-multilearn

Defaulting to user installation because normal site-packages is not writeable


In [10]:
from skmultilearn.problem_transform import BinaryRelevance
from skmultilearn.problem_transform import ClassifierChain
from skmultilearn.problem_transform import LabelPowerset

In [11]:
!pip install neattext

Defaulting to user installation because normal site-packages is not writeable
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              0.0/114.7 kB ? eta -:--:--
                                              

In [12]:
import neattext as nt
import neattext.functions as nfx

In [13]:
df['title'].apply(lambda x:nt.TextFrame(x).noise_scan())

0      {'text_noise': 11.267605633802818, 'text_lengt...
1      {'text_noise': 4.651162790697675, 'text_length...
2      {'text_noise': 9.90990990990991, 'text_length'...
3      {'text_noise': 8.47457627118644, 'text_length'...
4      {'text_noise': 2.631578947368421, 'text_length...
                             ...                        
139    {'text_noise': 26.41509433962264, 'text_length...
140    {'text_noise': 3.8461538461538463, 'text_lengt...
141    {'text_noise': 6.666666666666667, 'text_length...
142    {'text_noise': 13.636363636363635, 'text_lengt...
143    {'text_noise': 7.142857142857142, 'text_length...
Name: title, Length: 144, dtype: object

In [14]:
df['title'].apply(lambda x:nt.TextExtractor(x).extract_stopwords())

0                                [when, are, the, and]
1                                           [two, for]
2                    [the, of, that, a, and, the, and]
3                                    [in, a, and, and]
4                                              [using]
                            ...                       
139                                 [where, in, using]
140                                               [to]
141                                  [and, get, using]
142    [how, to, the, of, a, with, a, back, into, the]
143                                           [in, if]
Name: title, Length: 144, dtype: object

In [15]:
df['title'].apply(nfx.remove_stopwords)

0      Flask-SQLAlchemy - tables/databases created de...
1                    Combining PHP variables MySQL query
2      'Counting' number records match certain criter...
3         Insert new row table auto id number. Php MySQL
4                       Create Multiple MySQL tables PHP
                             ...                        
139               Executing "SELECT ... ... ..." MySQLdb
140                              SQLAlchemy reconnect db
141                      mysql Count Distinct result php
142    store result radio button database value, data...
143                 Use SQL count result statement - PHP
Name: title, Length: 144, dtype: object

In [16]:
corpus = df['title'].apply(nfx.remove_stopwords)

In [17]:
tfidf = TfidfVectorizer()
Xfeatures = tfidf.fit_transform(corpus).toarray()
Xfeatures

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [18]:
y = df[['mysql', 'python', 'php']]
X_train,X_test,y_train,y_test = train_test_split(Xfeatures,y,test_size=0.3,random_state=42)


In [19]:
binary_rel_clf = BinaryRelevance(MultinomialNB())
binary_rel_clf.fit(X_train,y_train)


BinaryRelevance(classifier=MultinomialNB(), require_dense=[True, True])

In [20]:
br_prediction = binary_rel_clf.predict(X_test)
br_prediction.toarray()

array([[1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [21]:
ex1 = df['title'].iloc[0]

In [22]:
vec_example = tfidf.transform([ex1])
binary_rel_clf.predict(vec_example).toarray()

array([[1., 1., 0.]])